### ISSUE TITLE
Error During Server Connection (1.19.8)

### ISSUE THREAD

**Issue by An-Sar** [Chronolegionnaire/HydrateOrDiedrate#21]
This error occurs when a player tries to connect to a server, it loops and prevents connection.

First encountered with version v1.3.1, and tested again with v1.3.5, not other mods installed.

```
29.9.2024 19:45:00 [Server Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.EntityPlayer.get_RightHandItemSlot() in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 149
   at HydrateOrDiedrate.WaterInteractionHandler.CheckPlayerInteraction(Single dt) in C:\Users\bryan\RiderProjects\HydrateOrDiedrate\HydrateOrDiedrate\src\WaterInteractionHandler.cs:line 114
   at Vintagestory.Common.GameTickListener.OnTriggered(Int64 ellapsedMilliseconds) in VintagestoryLib\Common\Model\GameTickListener.cs:line 27
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 57
   at Vintagestory.Server.CoreServerEventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Server\ServerEventManager.cs:line 123
   at Vintagestory.Server.ServerMain.Process() in VintagestoryLib\Server\ServerMain.cs:line 886
```

**Comment by Chronolegionnaire** [comment]
Could you try the test version and see if this resolves it?

https://drive.google.com/file/d/1qfZ2Ii4gxfTC3TLB7Ilol_0z4OqeZX9g/view?usp=sharing

**Comment by An-Sar** [comment]
Thanks for the test build, unfortunately the error still occurs with 1.3.7TEST.zip

**Comment by Chronolegionnaire** [comment]
https://drive.google.com/file/d/1FzRX18kSUI_lMSCwU1hxJaC7LoezUNyB/view?usp=sharing

How about this?

**Comment by Chronolegionnaire** [comment]
Another user reported that this fix worked for them, released new versions on the moddb, if issue persists please let me know

**Comment by An-Sar** [comment]
The new release worked for me as well, thank you
