### ISSUE TITLE
1.20pre7 HoD hydrateordiedrate_1.4.6-pre.7.zip Server loop in errors

### ISSUE THREAD

**Issue by DejFidOFF** [Chronolegionnaire/HydrateOrDiedrate#22]
24.10.2024 19:44:33 [Error] Exception: Method not found: 'Void Vintagestory.API.MathTools.Vec3f.Set(Vintagestory.API.MathTools.Vec3f)'.
   at HydrateOrDiedrate.RainHarvesterData.SetParticleProperties(SimpleParticleProperties particles, Vec3d pos, Double addPos, Int32 quantity, Single gravityEffect, Vec3f velocity)
   at HydrateOrDiedrate.RainHarvesterData.SpawnRainParticles(Vec3d pos, Single rainIntensity) in C:\Users\bryan\RiderProjects\HydrateOrDiedrate\HydrateOrDiedrate\src\RainHarvesterData.cs:line 189
   at HydrateOrDiedrate.RainHarvesterData.OnParticleTickUpdate(Single deltaTime) in C:\Users\bryan\RiderProjects\HydrateOrDiedrate\HydrateOrDiedrate\src\RainHarvesterData.cs:line 154
   at HydrateOrDiedrate.RainHarvesterManager.OnTick(Single deltaTime) in C:\Users\bryan\RiderProjects\HydrateOrDiedrate\HydrateOrDiedrate\src\RainHarvestManager.cs:line 70
   at Vintagestory.Common.GameTickListener.OnTriggered(Int64 ellapsedMilliseconds) in VintagestoryLib\Common\Model\GameTickListener.cs:line 27
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 57
   at Vintagestory.Server.CoreServerEventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Server\ServerEventManager.cs:line 123
   at Vintagestory.Server.ServerMain.Process() in VintagestoryLib\Server\ServerMain.cs:line 904

**Comment by Chronolegionnaire** [comment]
I posted a test build in the discord thread for the mod, is this issue still present in that version?

**Comment by Chronolegionnaire** [comment]
Fixed in 1.4.6
