### ISSUE TITLE
Hydrate 1.5.2 causing shutdown server.

### ISSUE THREAD

**Issue by DejFidOFF** [Chronolegionnaire/HydrateOrDiedrate#24]
spamming server log with this:
8.11.2024 18:37:15 [Error] Exception: Method not found: 'Void Vintagestory.API.MathTools.Vec3f.Set(Vintagestory.API.MathTools.Vec3f)'.
   at HydrateOrDiedrate.RainHarvesterData.SetParticleProperties(SimpleParticleProperties particles, Vec3d pos, Double addPos, Int32 quantity, Single gravityEffect, Vec3f velocity)
   at HydrateOrDiedrate.RainHarvesterData.OnParticleTickUpdate(Single deltaTime) in C:\Users\bryan\RiderProjects\HydrateOrDiedrate\HydrateOrDiedrate\src\RainHarvesterData.cs:line 153
   at HydrateOrDiedrate.RainHarvesterManager.OnTick(Single deltaTime) in C:\Users\bryan\RiderProjects\HydrateOrDiedrate\HydrateOrDiedrate\src\RainHarvestManager.cs:line 77
   at Vintagestory.Common.GameTickListener.OnTriggered(Int64 ellapsedMilliseconds) in VintagestoryLib\Common\Model\GameTickListener.cs:line 27
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 57
   at Vintagestory.Server.ServerMain.Process() in VintagestoryLib\Server\ServerMain.cs:line 904

**Comment by Chronolegionnaire** [comment]
Is this 1.19 or 1.20

**Comment by DejFidOFF** [comment]
Sorry. I am running test server up to date so 1.20pre11

**Comment by Chronolegionnaire** [comment]
Actually I am unable to reproduce on both 1.19 and 1.20.

**Comment by Chronolegionnaire** [comment]
Could you potentially test an experimental build for me? I have a potential fix, but as I can't reproduce on my end, there's no way to tell if it works or not

**Comment by Chronolegionnaire** [comment]
[hydrateordiedrate_1.5.3-pre.11.zip](https://github.com/user-attachments/files/17684624/hydrateordiedrate_1.5.3-pre.11.zip)

**Comment by DejFidOFF** [comment]
Ok but tomorrow in the morning. Have CET here

**Comment by DejFidOFF** [comment]
It seems 1.5.3-pre11 works fine
