### ISSUE TITLE
Hydrate 1.5.9 Bowls no more collecting rain

### ISSUE THREAD

**Issue by DejFidOFF** [Chronolegionnaire/HydrateOrDiedrate#29]
Bowls on the ground no more collecting rain

20.12.2024 21:20:09 [Error] Error in RainHarvesterManager: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at HydrateOrDiedrate.RainHarvesterManager.<OnInactiveHarvesterCheck>b__17_0() in C:\Users\bryan\RiderProjects\HydrateOrDiedrate\HydrateOrDiedrate\src\RainHarvestManager.cs:line 182
   at HydrateOrDiedrate.RainHarvesterManager.ProcessTaskQueue() in C:\Users\bryan\RiderProjects\HydrateOrDiedrate\HydrateOrDiedrate\src\RainHarvestManager.cs:line 202

**Comment by Chronolegionnaire** [comment]
Fixed in 1.6.0, thanks for the report. Will try to get 1.6.0 pushed this weekend.
